### ISSUE TITLE
Page numbering extension: header position bug

### ISSUE THREAD

**Issue by topoldo** [eellak/gsoc2018-librecust#86] opened 2018-08-17 12:59 UTC
There is at least a bug in the managing the style.
If you compare the position of page number as set with the default LibO (v. 6.0.6.2) and by usin Numbering addon extension you see what is reported in the attached image1.jpg and image2.jpg
![image1](https://user-images.githubusercontent.com/9356777/44267348-218ec480-a22e-11e8-8a31-98a13f51d04f.jpg)
![image2](https://user-images.githubusercontent.com/9356777/44267355-2784a580-a22e-11e8-8133-cd4f276b046d.jpg)

**Comment by arvchristos** [comment] 2018-08-17 16:26
Thank you @topoldo ! 
Let me test and confirm the issue.

**Comment by arvchristos** [comment] 2018-08-21 17:46
THe issue is fixed with the latest pull request ( https://github.com/eellak/gsoc2018-librecust/commit/48a34e514c48680ccbb1f4a7a26803481c68064e)

**Closed** 2018-08-21 17:55 UTC
Labels: bug, confirmed
